# Copy Bluefin CLI packages
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/atuin /usr/bin/atuin
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/delta /usr/bin/delta
#COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/difftastic /usr/bin/difftastic
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/eza /usr/bin/eza
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/fd /usr/bin/fd
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/fzf /usr/bin/fzf
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/rg /usr/bin/rg
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/bin/zoxide /usr/bin/zoxide
COPY --from=ghcr.io/bayou-brogrammer/orora-cli /usr/share/bash-prexec /usr/share/bash-prexec
